name: Terraform Test

on: [push]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install terraform

      - name: Init Terraform repo
        run: |
          terraform init
          terraform plan